// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQovBIYQYfpaPJlpIriH21IIvtFM1QDtY',
    appId: '1:378358476741:web:3131f8b15841213801e5ac',
    messagingSenderId: '378358476741',
    projectId: 'fitlens-project',
    authDomain: 'fitlens-project.firebaseapp.com',
    storageBucket: 'fitlens-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFfplJ2YO9MJnzqJrq5sKLP4NRmTiy95s',
    appId: '1:28395191603:android:f446b64080a04582fe1246',
    messagingSenderId: '28395191603',
    projectId: 'fitlens-project-e33a8',
    storageBucket: 'fitlens-project-e33a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPm03O8oM_kLGGUSIMIk5YCRJFAB2opJc',
    appId: '1:378358476741:ios:35d9ca5272714edc01e5ac',
    messagingSenderId: '378358476741',
    projectId: 'fitlens-project',
    storageBucket: 'fitlens-project.firebasestorage.app',
    iosBundleId: 'com.example.fitlens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPm03O8oM_kLGGUSIMIk5YCRJFAB2opJc',
    appId: '1:378358476741:ios:35d9ca5272714edc01e5ac',
    messagingSenderId: '378358476741',
    projectId: 'fitlens-project',
    storageBucket: 'fitlens-project.firebasestorage.app',
    iosBundleId: 'com.example.fitlens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQovBIYQYfpaPJlpIriH21IIvtFM1QDtY',
    appId: '1:378358476741:web:83413b4db68ff65b01e5ac',
    messagingSenderId: '378358476741',
    projectId: 'fitlens-project',
    authDomain: 'fitlens-project.firebaseapp.com',
    storageBucket: 'fitlens-project.firebasestorage.app',
  );
}